fix(plugins): replace duplicity temp logfile by a pipe to avoid filling the tmpfs (fixes #45)

diff --git a/agent/plugins/duplicity b/agent/plugins/duplicity
--- a/agent/plugins/duplicity
+++ b/agent/plugins/duplicity
@@ -3,16 +3,13 @@
 set -e
 
 function checkWarnings {
-	set +e
-
-	grep -q WARNING /tmp/backup.log
-	if [[ $? -eq 0 ]]; then
+	if [ -s /tmp/banana-errors ]; then
 		>&2 echo "warnings were found in backup logs"
+		rm -f /tmp/banana-errors
 		exit 1
 	fi
-	rm -f /tmp/backup.log
 
-	set -e
+	rm -f /tmp/banana-errors
 }
 
 case $1 in
@@ -22,12 +19,12 @@ version)
 	;;
 
 backup)
-	>&2 duplicity $2 -v8 --log-file /tmp/backup.log "${@:4}" $3
+	>&2 duplicity $2 -v8 --log-fd 3 "${@:4}" $3 3> >(grep WARNING > /tmp/banana-errors)
 	checkWarnings
 	;;
 
 restore)
-	>&2 duplicity --log-file /tmp/backup.log --restore-time $2 $3 "${@:4}"
+	>&2 duplicity --log-fd 3 --restore-time $2 $3 "${@:4}" 3> >(grep WARNING > /tmp/banana-errors)
 	checkWarnings
 	;;
 
