feat(agent): output duplicity statistics as json

diff --git a/agent/plugins/duplicity b/agent/plugins/duplicity
--- a/agent/plugins/duplicity
+++ b/agent/plugins/duplicity
@@ -12,6 +12,53 @@ function checkWarnings {
 	rm -f /tmp/banana-errors
 }
 
+function generateMetadata {
+	while read -r line; do
+		key=$(echo "${line}" | sed -E 's/([a-zA-Z]*).*/\1/')
+		value=$(echo "${line}" | sed -E 's/[^ ]* *(.*)/\1/')
+
+		if [ ! -z ${key} ]; then local ${key}="${value}"; fi
+	done
+
+	jq -n \
+		--argjson size $(echo ${TotalDestinationSizeChange} | awk '{printf $1}') \
+		--arg StartTime "${StartTime}" \
+		--arg EndTime "${EndTime}" \
+		--arg ElapsedTime "${ElapsedTime}" \
+		--arg SourceFiles "${SourceFiles}" \
+		--arg SourceFileSize "${SourceFileSize}" \
+		--arg NewFiles "${NewFiles}" \
+		--arg NewFileSize "${NewFileSize}" \
+		--arg DeletedFiles "${DeletedFiles}" \
+		--arg ChangedFiles "${ChangedFiles}" \
+		--arg ChangedFileSize "${ChangedFileSize}" \
+		--arg ChangedDeltaSize "${ChangedDeltaSize}" \
+		--arg DeltaEntries "${DeltaEntries}" \
+		--arg RawDeltaSize "${RawDeltaSize}" \
+		--arg TotalDestinationSizeChange "${TotalDestinationSizeChange}" \
+		--arg Errors "${Errors}" \
+		'{
+			size: $size,
+			plugin_meta: {
+				StartTime: $StartTime,
+				EndTime: $EndTime,
+				ElapsedTime: $ElapsedTime,
+				SourceFiles: $SourceFiles,
+				SourceFileSize: $SourceFileSize,
+				NewFiles: $NewFiles,
+				NewFileSize: $NewFileSize,
+				DeletedFiles: $DeletedFiles,
+				ChangedFiles: $ChangedFiles,
+				ChangedFileSize: $ChangedFileSize,
+				ChangedDeltaSize: $ChangedDeltaSize,
+				DeltaEntries: $DeltaEntries,
+				RawDeltaSize: $RawDeltaSize,
+				TotalDestinationSizeChange: $TotalDestinationSizeChange,
+				Errors: $Errors
+			}
+		}'
+}
+
 case $1 in
 
 version)
@@ -19,7 +66,7 @@ version)
 	;;
 
 backup)
-	>&2 duplicity $2 -v4 --log-fd 3 "${@:4}" $3 3> >(grep WARNING > /tmp/banana-errors)
+	duplicity $2 -v4 --log-fd 3 "${@:4}" $3 3> >(grep WARNING > /tmp/banana-errors) | >&2 tee >(generateMetadata > metadata.json)
 	checkWarnings
 	;;
 
